Repository PagerDuty/terraform-provider-pagerduty, pull requests merged in 2018-11, with the labels that each got.

#99 Instantiate scheduled_actions if incident_urgency_rules with type = "use_support_hours"
  pagerduty/data_source_pagerduty_vendor_test.go
  pagerduty/resource_pagerduty_service.go
  pagerduty/resource_pagerduty_service_test.go
Labels: size/M

#100 Fix typo: should be 'schedule'
  website/docs/r/schedule.html.markdown
Labels: size/XS

#92 Docs: add valid user color options
  website/docs/r/user.html.markdown
Labels: documentation, size/XS
