Repository PagerDuty/terraform-provider-pagerduty, pull requests merged in 2019-10, with the labels that each got.

#157 Fixing issue with perpetual diff in event rules
  pagerduty/resource_pagerduty_event_rule.go
  pagerduty/resource_pagerduty_event_rule_test.go
Labels: size/M

#154 Update valid colors for users
  website/docs/r/user.html.markdown
Labels: documentation, size/XS

#160 Fixing Docs for Event Rules resource: Setting Advanced Condition to Optional
  website/docs/r/event_rule.html.markdown
Labels: documentation, size/XS

#162 Add html_url read-only attribute to pagerduty_service and fixes for others
  pagerduty/resource_pagerduty_extension.go
  pagerduty/resource_pagerduty_extension_test.go
  pagerduty/resource_pagerduty_service.go
  pagerduty/resource_pagerduty_service_test.go
  pagerduty/resource_pagerduty_team.go
  pagerduty/resource_pagerduty_team_test.go
  pagerduty/resource_pagerduty_user.go
  pagerduty/resource_pagerduty_user_test.go
  website/docs/r/extension.html.markdown
  website/docs/r/service.html.markdown
  website/docs/r/team.html.markdown
Labels: documentation, size/S
