Repository PagerDuty/terraform-provider-pagerduty, pull requests merged in 2019-08, with the labels that each got.

#143 service: Add support for alert_grouping and alert_grouping_timeout
  go.mod
  go.sum
  pagerduty/resource_pagerduty_service.go
  pagerduty/resource_pagerduty_service_test.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/event_rule.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/pagerduty.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/service.go
  vendor/modules.txt
  website/docs/r/service.html.markdown
Labels: dependencies, documentation, enhancement, size/L

#146 resource/pagerduty_user: deprecate teams attribute
  pagerduty/resource_pagerduty_team_membership_test.go
  pagerduty/resource_pagerduty_user.go
  pagerduty/resource_pagerduty_user_test.go
  website/docs/r/user.html.markdown
Labels: breaking-change, documentation, size/S

#148 resource/pagerduty_team_membership: Retry create on error
  pagerduty/provider.go
  pagerduty/resource_pagerduty_team_membership.go
Labels: bug, size/XS

#149 resource/resource_pagerduty_service: skip tests if missing ability
  pagerduty/provider_test.go
  pagerduty/resource_pagerduty_service_test.go
Labels: size/XS

#150 Adding Event Rule Resource
  CHANGELOG.md
  go.mod
  go.sum
  pagerduty/import_pagerduty_event_rule_test.go
  pagerduty/provider.go
  pagerduty/resource_pagerduty_event_rule.go
  pagerduty/resource_pagerduty_event_rule_test.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/event_rule.go
  website/docs/r/event_rule.html.markdown
  website/pagerduty.erb
Labels: dependencies, documentation, size/XL
