Repository PagerDuty/terraform-provider-pagerduty, pull requests merged in 2019-07, with the labels that each got.

#135 Remove invalid role types
  pagerduty/resource_pagerduty_user.go
  pagerduty/resource_pagerduty_user_test.go
Labels: size/XS

#138 Fix issues with user's teams not set properly and update user's roles
  pagerduty/resource_pagerduty_team_membership_test.go
  pagerduty/resource_pagerduty_user.go
Labels: size/XS

#133 Remove status as it is not required
  pagerduty/resource_pagerduty_service.go
Labels: size/XS

#106 Include severity_based for urgency rule in docs
  website/docs/r/service.html.markdown
Labels: documentation, size/XS

#141 Create data source for service resource
  pagerduty/data_source_pagerduty_service.go
  pagerduty/data_source_pagerduty_service_test.go
  pagerduty/provider.go
  website/docs/d/service.html.markdown
  website/pagerduty.erb
Labels: documentation, enhancement, size/L

#142 resource/pagerduty_maintenance_window: Allow services to be unordered
  pagerduty/resource_pagerduty_maintenance_window.go
  pagerduty/resource_pagerduty_maintenance_window_test.go
Labels: bug
