Repository PagerDuty/terraform-provider-pagerduty, pull requests merged in 2020-06, with the labels that each got.

#237 Adding Ruleset Data Source
  go.mod
  go.sum
  pagerduty/data_source_pagerduty_ruleset.go
  pagerduty/data_source_pagerduty_ruleset_test.go
  pagerduty/provider.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/error.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/pagerduty.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/ruleset.go
  vendor/modules.txt
  website/docs/d/priority.html.markdown
  website/docs/d/ruleset.html.markdown
  website/docs/r/team_membership.html.markdown
  website/docs/r/user.html.markdown
  website/pagerduty.erb
Labels: dependencies, documentation, size/XL

#238 Updating service_dependency to support technical service dependencies
  go.mod
  go.sum
  pagerduty/import_pagerduty_service_dependency_test.go
  pagerduty/resource_pagerduty_service_dependency.go
  pagerduty/resource_pagerduty_service_dependency_test.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/business_service.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/service_dependency.go
  vendor/modules.txt
  website/docs/r/service_dependency.html.markdown
Labels: dependencies, documentation, size/L

#239 Add example of referencing the Default Global Ruleset
  website/docs/d/ruleset.html.markdown
Labels: documentation, size/XS

#208 Implement retry logic in all read requests
  pagerduty/data_source_pagerduty_escalation_policy.go
  pagerduty/data_source_pagerduty_extension_schema.go
  pagerduty/data_source_pagerduty_schedule.go
  pagerduty/data_source_pagerduty_service.go
  pagerduty/data_source_pagerduty_team.go
  pagerduty/data_source_pagerduty_user.go
  pagerduty/data_source_pagerduty_vendor.go
  pagerduty/resource_pagerduty_addon.go
  pagerduty/resource_pagerduty_escalation_policy.go
  pagerduty/resource_pagerduty_event_rule.go
  pagerduty/resource_pagerduty_extension.go
  pagerduty/resource_pagerduty_maintenance_window.go
  pagerduty/resource_pagerduty_ruleset.go
  pagerduty/resource_pagerduty_ruleset_rule.go
  pagerduty/resource_pagerduty_schedule.go
  pagerduty/resource_pagerduty_service.go
  pagerduty/resource_pagerduty_service_integration.go
  pagerduty/resource_pagerduty_team.go
  pagerduty/resource_pagerduty_team_membership.go
  pagerduty/resource_pagerduty_user.go
  pagerduty/resource_pagerduty_user_contact_method.go
  pagerduty/resource_pagerduty_user_notification_rule.go
Labels: size/XL

#193 Bump golang to v1.14.1
  .go-version
  .travis.yml
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, size/L

#242 Extended example of adding multiple targets
  website/docs/r/escalation_policy.html.markdown
Labels: documentation, size/XS

#243 Extended example of alert_creation on service
  website/docs/r/service.html.markdown
Labels: documentation, size/XS

#244 Extending example of events apiv2 and email
  website/docs/r/service_integration.html.markdown
Labels: documentation, size/XS

#246 Added team to pagerduty_business_service resource
  pagerduty/resource_pagerduty_business_service.go
  pagerduty/resource_pagerduty_business_service_test.go
  pagerduty/resource_pagerduty_ruleset_rule.go
  website/docs/r/business_service.html.markdown
Labels: documentation, size/M

#248 Update user roles info
  website/docs/r/user.html.markdown
Labels: documentation, size/XS
