Repository PagerDuty/terraform-provider-pagerduty, pull requests merged in 2020-07, with the labels that each got.

#235 Fix alert grouping to be able to use the null value
  go.mod
  go.sum
  pagerduty/resource_pagerduty_service.go
Labels: size/XS

#257 Allowing "Removal" of Schedule Layers
  go.mod
  go.sum
  pagerduty/resource_pagerduty_schedule.go
  pagerduty/resource_pagerduty_schedule_test.go
  pagerduty/util.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/pagerduty.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/references.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/response_play.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/service.go
  vendor/modules.txt
Labels: dependencies, size/XL

#256 Add time_zone to pagerduty_user doc
  website/docs/r/user.html.markdown
Labels: documentation, size/XS

#258 adding retry logic to deleting schedule,team_membership and user
  pagerduty/resource_pagerduty_schedule.go
  pagerduty/resource_pagerduty_team_membership.go
  pagerduty/resource_pagerduty_user.go
Labels: size/S

#253 Service integration retry on create
  pagerduty/resource_pagerduty_service_integration.go
Labels: size/XS
