Repository PagerDuty/terraform-provider-pagerduty, pull requests merged in 2020-04, with the labels that each got.

#194 DOCS: Team membership role defaults to manager
  website/docs/r/team_membership.html.markdown
Labels: documentation, size/XS

#195 Adding Ruleset and Ruleset Rule Resources
  go.mod
  go.sum
  pagerduty/provider.go
  pagerduty/resource_pagerduty_ruleset.go
  pagerduty/resource_pagerduty_ruleset_rule.go
  pagerduty/resource_pagerduty_ruleset_rule_test.go
  pagerduty/resource_pagerduty_ruleset_test.go
  pagerduty/resource_pagerduty_schedule.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/business_service.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/event_rule.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/pagerduty.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/references.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/ruleset.go
  vendor/modules.txt
  website/docs/r/event_rule.html.markdown
  website/docs/r/ruleset.html.markdown
  website/docs/r/ruleset_rule.html.markdown
Labels: dependencies, documentation, size/XXL

#198 Fixing Docs to Include Ruleset and Rules in Side Nav
  website/docs/r/ruleset_rule.html.markdown
  website/pagerduty.erb
Labels: documentation, size/XS

#199 Fixing Importing for Rulesets and Ruleset Rules. Adding Import Tests.
  pagerduty/import_pagerduty_ruleset_rule_test.go
  pagerduty/import_pagerduty_ruleset_test.go
  pagerduty/resource_pagerduty_ruleset.go
  pagerduty/resource_pagerduty_ruleset_rule.go
  pagerduty/resource_pagerduty_ruleset_rule_test.go
  website/docs/r/ruleset.html.markdown
  website/docs/r/ruleset_rule.html.markdown
Labels: documentation, size/L

#205 Fixing Ruleset_Rule Import of Catch All Rules
  pagerduty/resource_pagerduty_ruleset_rule.go
Labels: size/XS

#214 resource_pagerduty_service_integration: Fix panic
  pagerduty/resource_pagerduty_service_integration.go
Labels: size/XS

#211 Fixing Multi-Rule Creation Bug and Suppress Rule bug
  pagerduty/resource_pagerduty_ruleset_rule.go
Labels: size/S

#213 Adding Resources for Business Service and Service Dependency
  go.mod
  go.sum
  pagerduty/data_source_pagerduty_business_service.go
  pagerduty/data_source_pagerduty_business_service_test.go
  pagerduty/import_pagerduty_business_service_test.go
  pagerduty/import_pagerduty_service_dependency_test.go
  pagerduty/provider.go
  pagerduty/resource_pagerduty_business_service.go
  pagerduty/resource_pagerduty_business_service_test.go
  pagerduty/resource_pagerduty_service_dependency.go
  pagerduty/resource_pagerduty_service_dependency_test.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/business_service.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/pagerduty.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/service_dependency.go
  vendor/modules.txt
  website/docs/d/business_service.html.markdown
  website/docs/r/business_service.html.markdown
  website/docs/r/service_dependency.html.markdown
  website/pagerduty.erb
Labels: dependencies, documentation, size/XXL

#218 resource_pagerduty_service: Fix panic
  pagerduty/resource_pagerduty_service.go
Labels: size/XS

#219 Adding pagerduty_priority data source
  go.mod
  go.sum
  pagerduty/data_source_pagerduty_priority.go
  pagerduty/data_source_pagerduty_priority_test.go
  pagerduty/provider.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/pagerduty.go
  vendor/github.com/heimweh/go-pagerduty/pagerduty/priority.go
  vendor/modules.txt
  website/docs/d/priority.html.markdown
  website/docs/r/ruleset_rule.html.markdown
  website/docs/r/service_dependency.html.markdown
Labels: dependencies, documentation, size/L

#221 Adding Priority Data Source to Side Nav
  website/pagerduty.erb
Labels: documentation, size/XS
