Repository PagerDuty/terraform-provider-pagerduty, pull requests merged in 2020-03, with the labels that each got.

#186 Add retry to team read and schedule read
  pagerduty/resource_pagerduty_schedule.go
  pagerduty/resource_pagerduty_team.go
Labels: size/M

#185 update doc to reflect deprecated field.
  website/docs/r/user.html.markdown
Labels: documentation, size/XS

#179 Doc: team_responder role was renamed observer
  website/docs/r/user.html.markdown
Labels: documentation, size/XS

#180 Feature: Resource User Notification Rule
  pagerduty/import_pagerduty_user_notification_rule_test.go
  pagerduty/provider.go
  pagerduty/resource_pagerduty_user_notification_rule.go
  pagerduty/resource_pagerduty_user_notification_rule_test.go
  website/docs/r/user_notification_rule.html.markdown
  website/pagerduty.erb
Labels: documentation, size/XL

#190 Fixing Bug in Service Resource Where alert_grouping_timeout wasn't saving 0 values
  go.mod
  go.sum
  pagerduty/resource_pagerduty_event_rule.go
  pagerduty/resource_pagerduty_service.go
  pagerduty/util.go
  website/docs/r/event_rule.html.markdown
Labels: documentation, size/S

#191 Implement retry logic in read requests for services and service integrations
  pagerduty/resource_pagerduty_service.go
  pagerduty/resource_pagerduty_service_integration.go
Labels: size/L
